right now added 2 code kinldy check
sach2212/javascripttut pull request #20
Opened 2023-09-23 09:08 UTC by sach2212

2023-09-23 09:36 UTC, NitkarshChourasia requested changes
# You are getting good, as compared to your first program.
### Some minor corrections are there, redo it, then submit.
Also, use "use strict" ; at the start of every js. It is a good practice.

2023-09-23 09:36 UTC, NitkarshChourasia commented on JavaScript/very_easy/[100] Recreating the abs() Function [VE].js
> +return  num<0 ? num* -1 :  num
If using IDE use a formatter.

2023-09-23 09:36 UTC, NitkarshChourasia commented on JavaScript/very_easy/[100] Recreating the abs() Function [VE].js
> +absolute(-1.217197940) ➞ 1.21719794
Run it at least in console, before commiting?
This won't run, because the answers should be in comments // ->

You just copy and pasted it, and didn't even cared to run it.
Use a IDE, with intellisense.

2023-09-23 09:36 UTC, NitkarshChourasia commented on JavaScript/very_easy/[100] Recreating the abs() Function [VE].js
> +absolute(-3.14) ➞ 3.14
Syntax error.

2023-09-23 09:36 UTC, NitkarshChourasia commented on JavaScript/very_easy/[100] Recreating the abs() Function [VE].js
> +
Check the output, you are making mistakes in running the programs.

2023-09-23 09:36 UTC, NitkarshChourasia commented on JavaScript/very_easy/[101] Is the Last Character an _N [VE].js
> +           [ 23-09-23 complete ]
Comment it.
Don't you run your program.
It will give you syntax error.
DO you use microsoft notepad?!

2023-09-23 09:36 UTC, NitkarshChourasia commented on JavaScript/very_easy/[101] Is the Last Character an _N [VE].js
> +   let   result =  isLastCharacterN("Aiden")
I think it won't be necessary to initiate it to the result variable.

2023-09-23 09:36 UTC, NitkarshChourasia commented on JavaScript/very_easy/[101] Is the Last Character an _N [VE].js
> +    return str.endsWith("n")
You can make two functions out of it.

2023-09-23 09:36 UTC, NitkarshChourasia commented on JavaScript/very_easy/[101] Is the Last Character an _N [VE].js
> +   return str[str.length-1]== "n" ? true :false
One is enough

2023-09-23 09:36 UTC, NitkarshChourasia commented on JavaScript/very_easy/[101] Is the Last Character an _N [VE].js
> +
"use strict"; 

syntax at the start of the js file.

2023-09-23 09:36 UTC, NitkarshChourasia commented on JavaScript/very_easy/[103] Less Than_ Greater Than [VE].js
> +[23-09-23]-completed
// make this commented.

2023-09-23 09:36 UTC, NitkarshChourasia commented on JavaScript/very_easy/[103] Less Than_ Greater Than [VE].js
> +[23-09-23]-completed
Oh, you complete and run at the end before committing you write it.

2023-09-23 10:39 UTC, sach2212 commented on JavaScript/very_easy/[100] Recreating the abs() Function [VE].js
> +absolute(-1.217197940) ➞ 1.21719794
actually there was mistake while pasting the code 
 i do in vs code  will do it properly

2023-09-24 08:34 UTC, merged

2023-09-24 09:30 UTC, NitkarshChourasia reviewed
Why merged? Let me merge it after reviewing it.
You just do PR(s).

2023-09-24 09:30 UTC, NitkarshChourasia commented on JavaScript/very_easy/[105] Count the Arguments [VE].js
>  //Your code should go here:
Research about 
```
"use strict;"
```

2023-09-24 09:30 UTC, NitkarshChourasia commented on JavaScript/very_easy/[105] Count the Arguments [VE].js
> +function numArgs(str){
Can spread syntax with rest also be used?
But that is not the problem asked for.
So, it is totally right, unless you are copying from somewhere,
Read the contents thoroughly that will only help.